name: Run Tests

on:
  workflow_call:

jobs:
  test:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: nigelm/gh_actions_python_poetry_setup@v1
        with:
          python-version: 3.10.2
          poetry-version: 1.1.12

      - name: Run pre-commit set
        run: make lint

# end
