name: Upload To Pypi

on:
  workflow_call:
    inputs:
      pypi-token:
        description: The pypi token to use for authentication
        required: true

jobs:
  upload:
    name: Upload To Pypi
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: nigelm/gh_actions_python_poetry_setup@v1
        with:
          python-version: 3.10.2
          poetry-version: 1.1.12
          fetch-depth: 0

      - run: poetry config repositories.test-pypi https://test.pypi.org/legacy/
      - run: poetry config pypi-token.test-pypi ${{ inputs.pypi-token }}
      - run: poetry publish --build --repository test-pypi

# end
